"""Deterministic, evidence-only change builders (used when no LLM is available, and as the constrained
skeleton the LLM may fill in). Nothing here asserts a claim that is not a verbatim `Fact`."""
from __future__ import annotations

import json
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from urllib.parse import urlparse

from app.domain.enums import ActionType
from app.interventions.changes import FileChange, ManualTask, ProposedChange, wrap_section
from app.interventions.facts import EvidenceItem, Fact, FactBase


def slugify(text: str, *, max_len: int = 40) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return (s[:max_len].rstrip("-")) or "change"


@dataclass
class PlanContext:
    incident_id: str
    incident_number: int | None
    incident_title: str
    org_name: str
    org_domain: str | None
    capability: str
    facts: FactBase
    evidence: list[EvidenceItem] = field(default_factory=list)
    target_url: str | None = None
    repo_path: str | None = None
    old_contents: dict[str, str] = field(default_factory=dict)
    content_root: str = ""
    extension: str = ".md"
    path_resolver: Callable[[str], str] | None = None

    @property
    def section_id(self) -> str:
        return f"incident-{self.incident_number if self.incident_number is not None else self.incident_id[:8]}"

    def path_for_url(self, url: str) -> str:
        if self.path_resolver:
            return self.path_resolver(url)
        path = urlparse(url).path.strip("/")
        path = re.sub(r"\.(html?|php|aspx?)$", "", path) or "index"
        root = self.content_root.strip("/")
        return f"{root}/{path}{self.extension}" if root else f"{path}{self.extension}"

    def new_path(self, folder: str, name: str) -> str:
        root = self.content_root.strip("/")
        slug = slugify(name, max_len=60)
        base = f"{folder}/{slug}{self.extension}" if folder else f"{slug}{self.extension}"
        return f"{root}/{base}" if root else base

    @property
    def own_facts(self) -> list[Fact]:
        return self.facts.of("canonical", "owned")


@dataclass
class TemplateResult:
    change: ProposedChange | None
    reason: str | None = None


def _src_comment(facts: list[Fact]) -> str:
    refs = []
    for f in facts:
        when = f.retrieved_at.date().isoformat() if f.retrieved_at else "n/a"
        refs.append(f"{f.id} {f.url or 'canonical-knowledge'} retrieved {when}")
    return "<!-- sources: " + "; ".join(refs) + " -->" if refs else ""


def _fresh(ctx: PlanContext, facts: list[Fact], path: str | None) -> list[Fact]:
    old = ctx.old_contents.get(path or "", "")
    return [f for f in facts if f.text not in old]


def faq_markdown(ctx: PlanContext, facts: list[Fact], *, level: str = "###") -> str:
    cap, org = ctx.capability, ctx.org_name
    cap_tokens = {w.lower() for w in re.findall(r"[A-Za-z0-9]+", cap) if len(w) > 2}
    direct = [f for f in facts if cap_tokens & {w.lower() for w in re.findall(r"[A-Za-z0-9]+", f.text)}]
    rest = [f for f in facts if f not in direct]
    lines = [f"{level} Frequently asked questions", ""]
    if direct:
        lines += [f"**Does {org} support {cap}?**", "", direct[0].text, ""]
        rest = direct[1:] + rest
    if rest:
        lines += [f"**What else does {org} document about {cap}?**", ""]
        lines += [f"- {f.text}" for f in rest]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _body(ctx: PlanContext, facts: list[Fact], *, h1: bool) -> str:
    head = f"# {ctx.capability}" if h1 else f"## {ctx.capability}"
    parts = [head, "", *[f"- {f.text}" for f in facts], "", faq_markdown(ctx, facts, level="##" if h1 else "###"),
             _src_comment(facts), "<!-- generated by AEO SRE from cited evidence only; review before merge -->"]
    return "\n".join(parts)


def update_existing_page(ctx: PlanContext) -> TemplateResult:
    if not ctx.target_url and not ctx.repo_path:
        return TemplateResult(None, "no owned page URL or repo path is known for this incident")
    path = ctx.repo_path or ctx.path_for_url(ctx.target_url or "")
    facts = _fresh(ctx, ctx.own_facts, path)
    if not facts:
        return TemplateResult(None, "no grounded owned/canonical facts to write (cannot invent content)")
    old = ctx.old_contents.get(path)
    section = wrap_section(ctx.section_id, _body(ctx, facts, h1=False))
    fc = FileChange(path=path, old_content=old, new_content=section, change_type="update",
                    patch_mode="upsert_section", section_id=ctx.section_id)
    return TemplateResult(ProposedChange(
        title=f"Add explicit {ctx.capability} section to {path}", files=[fc], target_url=ctx.target_url,
        summary=f"Add/replace a delimited '{ctx.capability}' section with an FAQ built from {len(facts)} cited "
                f"evidence sentence(s).", fact_ids=[f.id for f in facts]))


def _new_page(ctx: PlanContext, *, folder: str, name: str, title: str, summary: str, body: str,
              facts: list[Fact], url_hint: str | None) -> TemplateResult:
    path = ctx.new_path(folder, name)
    exists = path in ctx.old_contents
    fc = FileChange(path=path, old_content=ctx.old_contents.get(path), new_content=wrap_section(ctx.section_id, body),
                    change_type="update" if exists else "create", patch_mode="upsert_section" if exists else "replace",
                    section_id=ctx.section_id if exists else None)
    notes = ["new page path is a proposal derived from the capability name; adjust to your site structure"]
    return TemplateResult(ProposedChange(title=title, files=[fc], target_url=url_hint, summary=summary,
                                         fact_ids=[f.id for f in facts], notes=notes))


def create_canonical_page(ctx: PlanContext) -> TemplateResult:
    facts = ctx.own_facts
    if not facts:
        return TemplateResult(None, "no grounded owned/canonical facts to write (cannot invent content)")
    url = f"https://{ctx.org_domain}/{slugify(ctx.capability, max_len=60)}" if ctx.org_domain else None
    return _new_page(ctx, folder="", name=ctx.capability, title=f"Create canonical page: {ctx.capability}",
                     summary=f"New canonical page for '{ctx.capability}' built from {len(facts)} cited sentence(s).",
                     body=_body(ctx, facts, h1=True), facts=facts, url_hint=url)


def create_faq(ctx: PlanContext) -> TemplateResult:
    facts = ctx.own_facts
    if not facts:
        return TemplateResult(None, "no grounded owned/canonical facts to write (cannot invent content)")
    body = "\n".join([f"# {ctx.capability}: frequently asked questions", "", faq_markdown(ctx, facts, level="##"),
                      _src_comment(facts), "<!-- generated by AEO SRE from cited evidence only; review before merge -->"])
    url = f"https://{ctx.org_domain}/faq/{slugify(ctx.capability, max_len=60)}" if ctx.org_domain else None
    return _new_page(ctx, folder="faq", name=ctx.capability, title=f"Create FAQ: {ctx.capability}",
                     summary=f"FAQ page for '{ctx.capability}' built from {len(facts)} cited sentence(s).",
                     body=body, facts=facts, url_hint=url)


def create_comparison_content(ctx: PlanContext) -> TemplateResult:
    own = ctx.own_facts
    if not own:
        return TemplateResult(None, "no grounded owned/canonical facts to write (cannot invent content)")
    comp = ctx.facts.of("competitor")
    comp_host = next((urlparse(f.url).netloc for f in comp if f.url), None)
    comp_name = comp_host or "alternatives"
    lines = [f"# {ctx.org_name} and {comp_name}: {ctx.capability}", "", f"## What {ctx.org_name} documents", "",
             *[f"- {f.text}" for f in own], ""]
    if comp:
        lines += [f"## What {comp_name} publishes", ""]
        for f in comp:
            when = f.retrieved_at.date().isoformat() if f.retrieved_at else "date unknown"
            lines.append(f"> {f.text}\n> Source: {f.url} (retrieved {when})\n")
    note = ("<!-- generated by AEO SRE from cited evidence only; competitor statements are quoted, "
            "not paraphrased; review before merge -->")
    lines += [_src_comment(own + comp), note]
    url = f"https://{ctx.org_domain}/compare/{slugify(ctx.capability, max_len=60)}" if ctx.org_domain else None
    res = _new_page(ctx, folder="compare", name=f"{comp_name}-{ctx.capability}",
                    title=f"Create comparison content: {ctx.capability}",
                    summary=f"Comparison page built from {len(own)} owned and {len(comp)} quoted competitor "
                            f"sentence(s).", body="\n".join(lines), facts=own + comp, url_hint=url)
    if not comp and res.change:
        res.change.notes.append("no competitor evidence was available: page lists owned facts only")
    return res


def publisher_outreach(ctx: PlanContext) -> TemplateResult:
    ext = [f for f in ctx.facts.of("external")]
    own = ctx.own_facts
    if not ext:
        return TemplateResult(None, "no third-party source evidence identifies a publisher to contact")
    if not own:
        return TemplateResult(None, "no grounded owned/canonical facts to cite in the outreach")
    src, truth = ext[0], own[0]
    host = urlparse(src.url or "").netloc or None
    body = (f"Hello,\n\nWe noticed that {src.url or 'your page'} says:\n\n  \"{src.text}\"\n\n"
            f"Our current documentation says:\n\n  \"{truth.text}\""
            f"{f' ({truth.url})' if truth.url else ''}\n\n"
            f"Could you review the statement and update it if appropriate? Happy to provide more detail.\n\n"
            f"Thank you,\n{ctx.org_name}\n")
    task = ManualTask(kind="publisher_outreach", title=f"Outreach to {host or 'publisher'}: {ctx.capability}",
                      body=body, recipient=host, target_url=src.url,
                      payload={"quoted_source_fact": src.id, "quoted_truth_fact": truth.id},
                      checklist=["Find the correct editorial contact", "Review the draft against the cited sources",
                                 "Send manually from a company account", "Record the response in the incident"])
    return TemplateResult(ProposedChange(kind="manual_task", title=task.title, target_url=src.url,
                                         summary="Drafted outreach quoting only cited evidence; no external "
                                                 "mutation is performed by AEO SRE.", manual_task=task,
                                         fact_ids=[src.id, truth.id]))


def structured_data(ctx: PlanContext) -> TemplateResult:
    own = ctx.own_facts
    if not own:
        return TemplateResult(None, "no grounded owned/canonical facts for structured data")
    entities = [{"@type": "Question", "name": f"What does {ctx.org_name} document about {ctx.capability}?",
                 "acceptedAnswer": {"@type": "Answer", "text": f.text}} for f in own[:6]]
    jsonld = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": entities}
    snippet = '<script type="application/ld+json">\n' + json.dumps(jsonld, indent=2) + "\n</script>"
    task = ManualTask(kind="structured_data", title=f"Add FAQPage JSON-LD for {ctx.capability}", body=snippet,
                      target_url=ctx.target_url, payload={"jsonld": jsonld},
                      checklist=["Validate with a structured-data testing tool",
                                 "Place in the page <head> on the target page",
                                 "Confirm the visible page content matches every answer"])
    return TemplateResult(ProposedChange(kind="manual_task", title=task.title, target_url=ctx.target_url,
                                         summary=f"FAQPage JSON-LD draft from {len(entities)} cited sentence(s); "
                                                 "applied manually.", manual_task=task,
                                         fact_ids=[f.id for f in own[:6]]))


def observe(ctx: PlanContext) -> TemplateResult:
    task = ManualTask(kind="observe", title=f"Monitor: {ctx.incident_title}",
                      body="No change is made. Continue monitoring the affected prompt cluster and re-evaluate "
                           "after the next measurement window.",
                      checklist=["Re-run visibility/citation measurements after the verification window",
                                 "Escalate if the metric degrades further"])
    return TemplateResult(ProposedChange(kind="observe", title=task.title, summary=task.body, manual_task=task))


BUILDERS: dict[ActionType, Callable[[PlanContext], TemplateResult]] = {
    ActionType.OBSERVE: observe,
    ActionType.UPDATE_EXISTING_PAGE: update_existing_page,
    ActionType.CREATE_FAQ: create_faq,
    ActionType.CREATE_CANONICAL_PAGE: create_canonical_page,
    ActionType.CREATE_COMPARISON_CONTENT: create_comparison_content,
    ActionType.PUBLISHER_OUTREACH: publisher_outreach,
    ActionType.STRUCTURED_DATA: structured_data,
}


def build_template(action: ActionType, ctx: PlanContext) -> TemplateResult:
    return BUILDERS[action](ctx)
