"""Profound connector. Profound-specific payload structures stay inside this package."""

from .capabilities import DOC_CONFIDENCE, SURFACES, CapabilityStatus
from .client import DEFAULT_BASE_URL, ProfoundClient, ProfoundResponse
from .errors import (
    ProfoundAuthError,
    ProfoundError,
    ProfoundNotConfigured,
    ProfoundNotFound,
    ProfoundPermissionError,
    ProfoundRateLimited,
    ProfoundResponseError,
    ProfoundServerError,
    ProfoundTransportError,
    ProfoundValidationError,
)
from .normalize import (
    NormalizedAsset,
    NormalizedCategory,
    NormalizedPrompt,
    NormalizedSignal,
    normalize_assets,
    normalize_categories,
    normalize_citations,
    normalize_factcheck,
    normalize_fanouts,
    normalize_prompts,
    normalize_visibility,
    normalize_volume,
)
from .requests import (
    CitationsQuery,
    FactCheckClaimsQuery,
    FactCheckQuery,
    FilterNode,
    PromptsListQuery,
    QueryFanoutsQuery,
    VisibilityQuery,
    VolumeQuery,
)
from .store import FileRawPayloadStore, InMemoryRawPayloadStore, RawPayloadStore

__all__ = [
    "DEFAULT_BASE_URL",
    "DOC_CONFIDENCE",
    "SURFACES",
    "CapabilityStatus",
    "CitationsQuery",
    "FactCheckClaimsQuery",
    "FactCheckQuery",
    "FileRawPayloadStore",
    "FilterNode",
    "InMemoryRawPayloadStore",
    "NormalizedAsset",
    "NormalizedCategory",
    "NormalizedPrompt",
    "NormalizedSignal",
    "ProfoundAuthError",
    "ProfoundClient",
    "ProfoundError",
    "ProfoundNotConfigured",
    "ProfoundNotFound",
    "ProfoundPermissionError",
    "ProfoundRateLimited",
    "ProfoundResponse",
    "ProfoundResponseError",
    "ProfoundServerError",
    "ProfoundTransportError",
    "ProfoundValidationError",
    "PromptsListQuery",
    "QueryFanoutsQuery",
    "RawPayloadStore",
    "VisibilityQuery",
    "VolumeQuery",
    "normalize_assets",
    "normalize_categories",
    "normalize_citations",
    "normalize_factcheck",
    "normalize_fanouts",
    "normalize_prompts",
    "normalize_visibility",
    "normalize_volume",
]
