"""Provider-neutral model runtime. See docs/notes/handoff-b3.md (B3) and handoff-a15.md (original client)."""
from app.connectors.llm.client import (
    LLMResult,
    ModelClient,
    ModelRouter,
    SyncModelClient,
    SyncModelRouter,
    UnavailableLLM,
    create_model_gateway,
    get_llm_client,
    get_llm_or_unavailable,
    get_sync_llm_client,
)
from app.connectors.llm.errors import (
    LLMAuthError,
    LLMError,
    LLMInvalidOutput,
    LLMModelNotFound,
    LLMUnavailable,
)
from app.connectors.llm.gateway import (
    ModelCallMeta,
    ModelCapabilities,
    ModelGateway,
    ModelHealth,
    ModelHealthState,
    ModelMessage,
    ModelPurpose,
    ModelRequest,
    ModelResponse,
    ModelTier,
    UnsupportedModelProtocol,
    estimate_cost_usd,
)
from app.connectors.llm.prompts import build_user_prompt, untrusted_block
from app.connectors.llm.registry import PROMPTS, PromptSpec, get_prompt
from app.connectors.llm.status import LLMCapability, current_health, llm_capability, recent_calls

__all__ = [
    "PROMPTS",
    "LLMAuthError",
    "LLMCapability",
    "LLMError",
    "LLMInvalidOutput",
    "LLMModelNotFound",
    "LLMResult",
    "LLMUnavailable",
    "ModelCallMeta",
    "ModelCapabilities",
    "ModelClient",
    "ModelGateway",
    "ModelHealth",
    "ModelHealthState",
    "ModelMessage",
    "ModelPurpose",
    "ModelRequest",
    "ModelResponse",
    "ModelRouter",
    "ModelTier",
    "PromptSpec",
    "SyncModelClient",
    "SyncModelRouter",
    "UnavailableLLM",
    "UnsupportedModelProtocol",
    "build_user_prompt",
    "create_model_gateway",
    "current_health",
    "estimate_cost_usd",
    "get_llm_client",
    "get_llm_or_unavailable",
    "get_prompt",
    "get_sync_llm_client",
    "llm_capability",
    "recent_calls",
    "untrusted_block",
]
