"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 18:27:33.036697
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS incident_number_seq')
    op.execute('CREATE SEQUENCE IF NOT EXISTS incident_event_seq')
    op.execute('CREATE SEQUENCE IF NOT EXISTS experiment_number_seq')
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_at'), 'audit_events', ['at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('competitor_domains', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('canonical_domains', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('personas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_domain'), 'organizations', ['domain'], unique=True)
    op.create_table('policy_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('priors', sa.JSON(), nullable=False),
    sa.Column('n_updates', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('source_experiment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_experiment_id')
    )
    op.create_index(op.f('ix_policy_versions_parent_id'), 'policy_versions', ['parent_id'], unique=False)
    op.create_index(op.f('ix_policy_versions_version'), 'policy_versions', ['version'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('policy_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('policy_version_id', sa.Uuid(), nullable=False),
    sa.Column('context_vector', sa.JSON(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('selected_action', sa.String(length=48), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('selection_basis', sa.String(length=32), nullable=False),
    sa.Column('cold_start', sa.Boolean(), nullable=False),
    sa.Column('n_related', sa.Integer(), nullable=False),
    sa.Column('allowed_actions', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_incident_id'), 'policy_decisions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_policy_version_id'), 'policy_decisions', ['policy_version_id'], unique=False)
    op.create_table('prompt_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('prompts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_clusters_org_id'), 'prompt_clusters', ['org_id'], unique=False)
    op.create_index(op.f('ix_prompt_clusters_topic'), 'prompt_clusters', ['topic'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('priority_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_cluster_id', sa.Uuid(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('investigation_status', sa.String(length=32), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_cluster_id'], ['prompt_clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_number'), 'incidents', ['number'], unique=True)
    op.create_index(op.f('ix_incidents_org_id'), 'incidents', ['org_id'], unique=False)
    op.create_index(op.f('ix_incidents_prompt_cluster_id'), 'incidents', ['prompt_cluster_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_state'), 'incidents', ['state'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prompt_cluster_id', sa.Uuid(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw_payload_ref', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_cluster_id'], ['prompt_clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_observed_at'), 'signals', ['observed_at'], unique=False)
    op.create_index(op.f('ix_signals_org_id'), 'signals', ['org_id'], unique=False)
    op.create_index('ix_signals_org_kind_observed', 'signals', ['org_id', 'kind', 'observed_at'], unique=False)
    op.create_index(op.f('ix_signals_prompt_cluster_id'), 'signals', ['prompt_cluster_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('retrieval_method', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('support_score', sa.Float(), nullable=True),
    sa.Column('contradiction_score', sa.Float(), nullable=True),
    sa.Column('insufficient_score', sa.Float(), nullable=True),
    sa.Column('freshness_risk', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_content_hash'), 'evidence', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_index('ix_evidence_incident_type', 'evidence', ['incident_id', 'type'], unique=False)
    op.create_table('evidence_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('src_id', sa.Uuid(), nullable=False),
    sa.Column('dst_id', sa.Uuid(), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_edges_dst_id'), 'evidence_edges', ['dst_id'], unique=False)
    op.create_index(op.f('ix_evidence_edges_incident_id'), 'evidence_edges', ['incident_id'], unique=False)
    op.create_index('ix_evidence_edges_incident_src_dst', 'evidence_edges', ['incident_id', 'src_id', 'dst_id'], unique=False)
    op.create_index(op.f('ix_evidence_edges_src_id'), 'evidence_edges', ['src_id'], unique=False)
    op.create_table('evidence_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('retrieval_method', sa.String(length=64), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_nodes_incident_id'), 'evidence_nodes', ['incident_id'], unique=False)
    op.create_index('ix_evidence_nodes_incident_kind', 'evidence_nodes', ['incident_id', 'kind'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('produced_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_incident_id'), 'hypotheses', ['incident_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_index('ix_incident_events_incident_seq', 'incident_events', ['incident_id', 'seq'], unique=False)
    op.create_index(op.f('ix_incident_events_seq'), 'incident_events', ['seq'], unique=True)
    op.create_table('interventions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('observe', 'update_existing_page', 'create_faq', 'create_canonical_page', 'create_comparison_content', 'publisher_outreach', 'structured_data', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('risk', sa.Enum('low', 'medium', 'high', name='risk', native_enum=False, length=32), nullable=False),
    sa.Column('proposed_change', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('selection_basis', sa.Enum('cold_start_prior', 'learned_policy', 'rule_fallback', 'manual_override', name='selectionbasis', native_enum=False, length=32), nullable=True),
    sa.Column('policy_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_hypothesis_id'), 'interventions', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_interventions_incident_id'), 'interventions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_interventions_policy_version_id'), 'interventions', ['policy_version_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intervention_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'modified', 'expired', name='approvalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('modified_change', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('requested_actor_type', sa.String(length=16), nullable=False),
    sa.Column('decided_actor_type', sa.String(length=16), nullable=True),
    sa.Column('requested_change', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_intervention_id'), 'approvals', ['intervention_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intervention_id', sa.Uuid(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('executor', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=1024), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('package', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('actual_change', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('deviation', sa.Boolean(), nullable=False),
    sa.Column('executed_by', sa.String(length=255), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_approval_id'), 'executions', ['approval_id'], unique=False)
    op.create_index(op.f('ix_executions_intervention_id'), 'executions', ['intervention_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('intervention_id', sa.Uuid(), nullable=False),
    sa.Column('policy_version_id', sa.Uuid(), nullable=True),
    sa.Column('policy_probability', sa.Float(), nullable=True),
    sa.Column('context_vector', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('alternatives', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('before_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('after_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'approved', 'executing', 'executed', 'awaiting_verification', 'verified', 'rewarded', 'rejected', 'failed', name='experimentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('verification_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('selected_action', sa.Enum('observe', 'update_existing_page', 'create_faq', 'create_canonical_page', 'create_comparison_content', 'publisher_outreach', 'structured_data', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('selection_basis', sa.Enum('cold_start_prior', 'learned_policy', 'rule_fallback', 'manual_override', name='selectionbasis', native_enum=False, length=32), nullable=True),
    sa.Column('cold_start', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('proposed_change', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('approved_change', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('approver', sa.String(length=255), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('executor', sa.String(length=64), nullable=True),
    sa.Column('execution_reference', sa.String(length=1024), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('timeline', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_incident_id'), 'experiments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_experiments_intervention_id'), 'experiments', ['intervention_id'], unique=False)
    op.create_index(op.f('ix_experiments_number'), 'experiments', ['number'], unique=True)
    op.create_index(op.f('ix_experiments_policy_version_id'), 'experiments', ['policy_version_id'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_experiment_id'), 'observations', ['experiment_id'], unique=False)
    op.create_index('ix_observations_experiment_observed', 'observations', ['experiment_id', 'observed_at'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_experiment_id'), 'rewards', ['experiment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewards_experiment_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index('ix_observations_experiment_observed', table_name='observations')
    op.drop_index(op.f('ix_observations_experiment_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_policy_version_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_number'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_intervention_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_incident_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_executions_intervention_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_approval_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_approvals_intervention_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_interventions_policy_version_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_incident_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_hypothesis_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_incident_events_seq'), table_name='incident_events')
    op.drop_index('ix_incident_events_incident_seq', table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_hypotheses_incident_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index('ix_evidence_nodes_incident_kind', table_name='evidence_nodes')
    op.drop_index(op.f('ix_evidence_nodes_incident_id'), table_name='evidence_nodes')
    op.drop_table('evidence_nodes')
    op.drop_index(op.f('ix_evidence_edges_src_id'), table_name='evidence_edges')
    op.drop_index('ix_evidence_edges_incident_src_dst', table_name='evidence_edges')
    op.drop_index(op.f('ix_evidence_edges_incident_id'), table_name='evidence_edges')
    op.drop_index(op.f('ix_evidence_edges_dst_id'), table_name='evidence_edges')
    op.drop_table('evidence_edges')
    op.drop_index('ix_evidence_incident_type', table_name='evidence')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_hash'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_signals_prompt_cluster_id'), table_name='signals')
    op.drop_index('ix_signals_org_kind_observed', table_name='signals')
    op.drop_index(op.f('ix_signals_org_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_observed_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_incidents_state'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_prompt_cluster_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_org_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_number'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_prompt_clusters_topic'), table_name='prompt_clusters')
    op.drop_index(op.f('ix_prompt_clusters_org_id'), table_name='prompt_clusters')
    op.drop_table('prompt_clusters')
    op.drop_index(op.f('ix_policy_decisions_policy_version_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_incident_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_table('settings')
    op.drop_index(op.f('ix_policy_versions_version'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_parent_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_organizations_domain'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_audit_events_at'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.execute('DROP SEQUENCE IF EXISTS experiment_number_seq')
    op.execute('DROP SEQUENCE IF EXISTS incident_event_seq')
    op.execute('DROP SEQUENCE IF EXISTS incident_number_seq')
    # ### end Alembic commands ###
