"""Change Guard: change_sets (immutable), change_checks (append-only), canonical_claims, approvals.action_digest

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 20:42:59.469017
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_by', sa.String(length=255), nullable=True),
    sa.Column('retire_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'retired')", name='ck_canonical_claims_status'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_claims_org_id'), 'canonical_claims', ['org_id'], unique=False)
    op.create_index('uq_canonical_claims_active_key', 'canonical_claims', ['org_id', 'key'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.create_table('change_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('intervention_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('profound_run_id', sa.String(length=128), nullable=True),
    sa.Column('source_mode', sa.String(length=16), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('target_key', sa.String(length=1024), nullable=False),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('proposed_claims', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('claims_raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_cluster_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prompts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=True),
    sa.Column('proposed_diff', sa.Text(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_kpi', sa.String(length=255), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=True),
    sa.Column('reversible', sa.Boolean(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('proposal_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("origin IN ('external', 'intervention')", name='ck_change_sets_origin'),
    sa.CheckConstraint("source_mode IN ('LIVE', 'SIMULATED')", name='ck_change_sets_source_mode'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'idempotency_key', name='uq_change_sets_org_idem')
    )
    op.create_index(op.f('ix_change_sets_intervention_id'), 'change_sets', ['intervention_id'], unique=False)
    op.create_index(op.f('ix_change_sets_org_id'), 'change_sets', ['org_id'], unique=False)
    op.create_index('ix_change_sets_org_target', 'change_sets', ['org_id', 'target_key'], unique=False)
    op.create_index(op.f('ix_change_sets_proposal_digest'), 'change_sets', ['proposal_digest'], unique=False)
    op.create_table('change_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('change_set_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('eligible_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_proposal', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('semantic_check', sa.String(length=32), nullable=False),
    sa.Column('guard_version', sa.String(length=32), nullable=False),
    sa.Column('action_digest', sa.String(length=64), nullable=False),
    sa.Column('experiment_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('experiment_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('ALLOW', 'MERGE', 'DELAY', 'REQUIRE_REVIEW', 'BLOCK')", name='ck_change_checks_decision'),
    sa.CheckConstraint("semantic_check IN ('ok', 'degraded', 'skipped_no_canonical_truth')", name='ck_change_checks_semantic'),
    sa.ForeignKeyConstraint(['change_set_id'], ['change_sets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_checks_action_digest'), 'change_checks', ['action_digest'], unique=False)
    op.create_index(op.f('ix_change_checks_change_set_id'), 'change_checks', ['change_set_id'], unique=False)
    op.create_index(op.f('ix_change_checks_decision'), 'change_checks', ['decision'], unique=False)
    op.create_index('ix_change_checks_org_created', 'change_checks', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_change_checks_org_id'), 'change_checks', ['org_id'], unique=False)
    op.add_column('approvals', sa.Column('action_digest', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###
    # Defence in depth beyond the ORM guards (app/models/changeguard.py): the database itself refuses UPDATE/DELETE of
    # an immutable ChangeSet / append-only ChangeCheck (TRUNCATE stays allowed for test cleanup). Postgres only.
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("""
            CREATE FUNCTION change_guard_append_only() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION '% rows are append-only (Change Guard)', TG_TABLE_NAME USING ERRCODE = 'restrict_violation';
            END;
            $$ LANGUAGE plpgsql
        """)
        for table in ('change_sets', 'change_checks'):
            op.execute(f'CREATE TRIGGER trg_{table}_append_only BEFORE UPDATE OR DELETE ON {table} '
                       'FOR EACH ROW EXECUTE FUNCTION change_guard_append_only()')


def downgrade() -> None:
    if op.get_bind().dialect.name == 'postgresql':
        for table in ('change_checks', 'change_sets'):
            op.execute(f'DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table}')
        op.execute('DROP FUNCTION IF EXISTS change_guard_append_only()')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approvals', 'action_digest')
    op.drop_index(op.f('ix_change_checks_org_id'), table_name='change_checks')
    op.drop_index('ix_change_checks_org_created', table_name='change_checks')
    op.drop_index(op.f('ix_change_checks_decision'), table_name='change_checks')
    op.drop_index(op.f('ix_change_checks_change_set_id'), table_name='change_checks')
    op.drop_index(op.f('ix_change_checks_action_digest'), table_name='change_checks')
    op.drop_table('change_checks')
    op.drop_index(op.f('ix_change_sets_proposal_digest'), table_name='change_sets')
    op.drop_index('ix_change_sets_org_target', table_name='change_sets')
    op.drop_index(op.f('ix_change_sets_org_id'), table_name='change_sets')
    op.drop_index(op.f('ix_change_sets_intervention_id'), table_name='change_sets')
    op.drop_table('change_sets')
    op.drop_index('uq_canonical_claims_active_key', table_name='canonical_claims', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_canonical_claims_org_id'), table_name='canonical_claims')
    op.drop_table('canonical_claims')
    # ### end Alembic commands ###
