"""graph outbox

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-03 21:20:22.045390
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE IF NOT EXISTS incident_number_seq')
    op.execute('CREATE SEQUENCE IF NOT EXISTS incident_event_seq')
    op.execute('CREATE SEQUENCE IF NOT EXISTS experiment_number_seq')
    op.create_table('graph_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=48), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dead_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graph_outbox_aggregate', 'graph_outbox', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_graph_outbox_created_at', 'graph_outbox', ['created_at'], unique=False)
    op.create_index('ix_graph_outbox_org_created', 'graph_outbox', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_graph_outbox_pending', 'graph_outbox', ['next_attempt_at', 'created_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL AND dead_at IS NULL'), sqlite_where=sa.text('processed_at IS NULL AND dead_at IS NULL'))
    op.create_index('ix_graph_outbox_processed_at', 'graph_outbox', ['processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_graph_outbox_processed_at', table_name='graph_outbox')
    op.drop_index('ix_graph_outbox_pending', table_name='graph_outbox', postgresql_where=sa.text('processed_at IS NULL AND dead_at IS NULL'), sqlite_where=sa.text('processed_at IS NULL AND dead_at IS NULL'))
    op.drop_index('ix_graph_outbox_org_created', table_name='graph_outbox')
    op.drop_index('ix_graph_outbox_created_at', table_name='graph_outbox')
    op.drop_index('ix_graph_outbox_aggregate', table_name='graph_outbox')
    op.drop_table('graph_outbox')
    op.execute('DROP SEQUENCE IF EXISTS experiment_number_seq')
    op.execute('DROP SEQUENCE IF EXISTS incident_event_seq')
    op.execute('DROP SEQUENCE IF EXISTS incident_number_seq')
    # ### end Alembic commands ###
